# Generated by Django 4.0.6 on 2022-07-09 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strongbank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaodadossensiveis',
            name='idcartao',
        ),
        migrations.RemoveField(
            model_name='cartaodadossensiveis',
            name='numero',
        ),
        migrations.AddField(
            model_name='cartao',
            name='dados_sensiveis',
            field=models.OneToOneField(default=100, on_delete=django.db.models.deletion.CASCADE, to='strongbank.cartaodadossensiveis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartao',
            name='numeracao',
            field=models.CharField(default='100', editable=False, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartao',
            name='tipo',
            field=models.CharField(choices=[('0', 'Credito'), ('1', 'Debito'), ('2', 'Credito e Debito')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('S', 'Saque'), ('D', 'Deposito'), ('TE', 'Transferência Efetuada'), ('TR', 'Transferência Recebida'), ('C', 'Cartão')], default='S', max_length=20),
        ),
    ]
