# Generated by Django 4.0.6 on 2022-07-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
